# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      fritzingTag:
        description: 'Fritzing version tag to build'
        required: true
        default: '0.9.6'
      boostTag:
        description: 'Boost version tag to use'
        required: true
        default: 'boost-1.78.0'
      libgit2:
        description: 'libgit2 version tag to use'
        required: true
        default: 'v0.28.5'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Build Parameters
        id: buildParameters
        run: |
          if (-Not "${{ github.event.inputs.fritzingTag }}")
          {
            # Push doesn't get workflow_dispatch values
            echo '::set-output name=fritzingTag::0.9.6'
            echo '::set-output name=boostTag::boost-1.78.0'
            echo '::set-output name=boostPath::boost_1_78_0'
            echo '::set-output name=libgit2Tag::v0.28.5'
          } else
          {
            echo '::set-output name=fritzingTag::${{ github.event.inputs.fritzingTag }}'
            echo '::set-output name=boostTag::${{ github.event.inputs.boostTag }}'
            $boostPath = "${{ github.event.inputs.boostTag }}".replace('-', '_').replace('.', '_')
            echo '::set-output name=boostPath::$boostPath'
            echo '::set-output name=libgit2Tag::${{ github.event.inputs.libgit2Tag }}'
          }
      
      - name: Show Inputs
        run: |
          echo "Fritzing Version: ${{ steps.buildParameters.outputs.fritzingTag }}"
          echo "Boost Version: ${{ steps.buildParameters.outputs.boostTag }}"
          echo "Boost Path: ${{ steps.buildParameters.outputs.boostPath }}"
          echo "LibGit2 Version: ${{ steps.buildParameters.outputs.libgit2Tag }}"
          
      - uses: actions/cache@v2
        id: cache-boost
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/${{ steps.buildParameters.outputs.boostPath }}
          key: ${{ runner.os }}-${{ steps.buildParameters.outputs.boostPath }}
          
      - uses: actions/cache@v2
        id: cache-libgit2
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/libgit2
          key: ${{ runner.os }}-${{ steps.buildParameters.outputs.libgit2Tag }}
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone Fritzing-App
        uses: actions/checkout@v2
        with:
          repository: fritzing/fritzing-app
          path: fritzing-app
          ref: '${{ steps.buildParameters.outputs.fritzingTag }}'
          submodules: recursive
      
      - name: Clone Fritzing-Parts
        uses: actions/checkout@v2
        with:
          repository: fritzing/fritzing-parts
          path: fritzing-parts
          submodules: recursive
      
      - name: Clone Boost
        uses: actions/checkout@v2
        if: steps.cache-boost.outputs.cache-hit != 'true'
        with:
          repository: boostorg/boost
          path: '${{ steps.buildParameters.outputs.boostPath }}'
          ref: '${{ steps.buildParameters.outputs.boostTag }}'
          submodules: recursive
      
      - run: dir
      
      - name: Bootstrap Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd ${{ steps.buildParameters.outputs.boostPath }}
          bootstrap
          cd %GITHUB_WORKSPACE%
          
      - name: Setup Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd ${{ steps.buildParameters.outputs.boostPath }}
          b2 headers
          dir boost
          cd %GITHUB_WORKSPACE%
      
      - name: Clone libgit2
        if: steps.cache-libgit2.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: libgit2/libgit2
          path: libgit2
          submodules: recursive
      
      - name: Build libgit2
        if: steps.cache-libgit2.outputs.cache-hit != 'true'
        run: |
          cd libgit2
          mkdir build64
          cd build64
          cmake ..
          cmake --build . --config Release
          cd $ENV:GITHUB_WORKSPACE

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.7
          dir: c:/
        
      - name: Build Fritzing x64
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          ./fritzing-app/tools/release_fritzing.bat '${{ steps.buildParameters.outputs.fritzingTag }}' 64 2017

      - name: Show Disk Usage
        if: always()
        run: get-PSDrive
