# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to build'
        required: true
        default: '0.9.6'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Build Parameters
        id: buildParameters
        run: |
          if (-Not "${{ github.event.inputs.tag }}")
          {
            # Push doesn't get workflow_dispatch values
            echo '::set-output name=tag::0.9.6'
          }
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: fritzing/fritzing-app
          path: fritzing-app
          ref: '${{ steps.buildParameters.outputs.tag }}'
      
      - uses: actions/checkout@v2
        with:
          repository: fritzing/fritzing-parts
          path: fritzing-parts
          
      - run: dir $ENV:GITHUB_WORKSPACE
